### ISSUE TITLE
usage of pysciter

### ISSUE THREAD

**Issue by Eliyanan** [pravic/pysciter#10]
i have downloaded pysciter recently, i have sciter sdk too. But i dont how to get start writing my .py code. I saw a minimal example that imorts sciter. I coudnt see the result, i am using pycharm ide and it says 'sciter' module can not be found. Please give me a guide how should i work with pysciter. Thanks..

**Comment by pravic** [comment]
> 'sciter' module can not be found. 

`pip install pysciter`

**Comment by Eliyanan** [comment]
why not sciter module included in the pycsiter, that i have downloaded from here?? then what is the use of forking from here after all!

**Comment by pravic** [comment]
Sorry, what are you mean? [pysciter/sciter](https://github.com/pravic/pysciter/tree/master/sciter) - it is a module.

**Comment by Eliyanan** [comment]
yeah i got that, why should i do download it in pip since i've download it from here. as you said there is pysciter/sciter directory but i couldnt see any sciter.py file, do i mis something? or can you tell how it works..

**Comment by pravic** [comment]
https://docs.python.org/3/tutorial/modules.html#packages

Python package can be either a file named `package.py` or a folder `package/__init__.py`.

**Comment by Eliyanan** [comment]
thank you it worked for me now.
