### ISSUE TITLE
Error load sciter-

### ISSUE THREAD

**Issue by samtux** [pravic/pysciter#8]
I get the next error in Arch Linux with Sciter SDK 3 and Python 3.2:

I append the PATH and LD_LIBRARY_PATH as export 

````
export PATH=$PATH:/opt/sciter-sdk-3/bin:/opt/sciter-sdk-3/bin.gtk
````

````
import sciter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/sciter/__init__.py", line 6, in <module>
    from .value import value as Value
  File "/usr/lib/python3.5/site-packages/sciter/value.py", line 15, in <module>
    _api = sciter.SciterAPI()
  File "/usr/lib/python3.5/site-packages/sciter/capi/scapi.py", line 478, in SciterAPI
    raise ImportError(SCITER_LOAD_ERROR)
ImportError: sciter-gtk-64.so was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) available at the path.

````

**Comment by pravic** [comment]
Try this:

```
sudo echo /opt/sciter-sdk-3/bin.gtk/sciter-gtk-64.so > /etc/ld.so.conf.d/sciter.conf
sudo ldconfig
```

**Comment by ealesid** [comment]
Hi

I got the same error:
`>>> import sciter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sciter/__init__.py", line 21, in <module>
    from .value import value as Value
  File "/usr/local/lib/python3.4/dist-packages/sciter/value.py", line 15, in <module>
    _api = sciter.SciterAPI()
  File "/usr/local/lib/python3.4/dist-packages/sciter/capi/scapi.py", line 489, in SciterAPI
    raise ImportError(SCITER_LOAD_ERROR)
ImportError: libsciter-gtk-64.so was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) available at the path.
`

My environment are:
`root@eos:~# cat /proc/version
Linux version 3.16.0-77-generic (buildd@lgw01-09) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016
root@eos:~# cat /etc/ld.so.conf.d/sciter.conf 
/opt/sciter-sdk/bin.gtk/libsciter-gtk-64.so
root@eos:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/sciter-sdk/bin:/opt/sciter-sdk/bin.gtk
root@eos:~# echo $LD_LIBRARY_PATH
/opt/sciter-sdk/bin:/opt/sciter-sdk/bin.gtk
root@eos:~# python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
`

**Comment by pravic** [comment]
Hi, what's your sciter version? I haven't tried sciter 4 yet.

**Comment by ealesid** [comment]
Yes, it is 4th
Thanks
I'll try to find 3rd and try with it

**Comment by pravic** [comment]
Okay, I'll look version 4 changes.

**Comment by ealesid** [comment]
i downloaded ver 3.3.3.3 from sciter's github and got the same result

**Comment by ealesid** [comment]
Hi

i found the root and fixed this issue at myself
my previous libstdc++.so.6 didnt support CXXABI_1.3.8
after update to new version all became ok

`ealesid@loki:~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_TM_1
CXXABI_FLOAT128
`

**Comment by pravic** [comment]
Okay then. I thought that you already checked Sciter SDK samples before using pysciter :)

**Comment by kingtelepuz5** [comment]
ImportError: libsciter-gtk.so was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) are available in the path.
libsciter-gtk.so: cannot open shared object file: No such file or directory
libsciter-gtk-64.so: cannot open shared object file: No such file or directory

ubuntu 20.04 
i am dowloands SDK but i am don't understad now to use this!
path where bin :
~/sciter-js-sdk/bin$ 
pls i am need help!
